version: '3.8'

services:
  # Spring Boot Application
  patient-hub-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - h2-database

  # H2 Database
  h2-database:
    image: "alpine/h2:latest"
    ports:
      - "1521:1521"
      - "8082:8082"
    volumes:
      - ./data:/opt/h2-data
    command: ["java", "-cp", "/opt/h2/bin/h2-1.4.200.jar", "org.h2.tools.Server", "-web", "-webAllowOthers", "-tcp", "-tcpAllowOthers", "-ifNotExists"]